run:
  tests: true
  timeout: 20m
  skip-dirs:
    - pkg/gen
  skip-files:
    - "zz_generated.deepcopy.go$"

linters:
  enable:
    - goconst
    - gocyclo
    - gofmt
    - goimports
    - gosec
    - govet
    - misspell
    - revive
    - unused
    - whitespace

linters-settings:
  goimports:
    local-prefixes: github.com/openservicemesh/osm

issues:
  exclude-rules:
    # Ignore error for ginkgo and gomega dot imports
    - linters:
        - revive
      source: ". \"github.com/onsi/(ginkgo|gomega)\""
      text: "dot imports"
    # Ignore error for test framework imports
    - linters:
        - revive
      source: ". \"github.com/openservicemesh/osm/tests/framework\""
      text: "dot imports"
    # Ignore error for package comments
    - linters:
        - revive
      text: "package-comments: should have a package comment"
    # Exclude staticcheck messages for deprecated function, variable or constant
    # This causes issues with package github.com/golang/protobuf/proto
    - linters:
        - staticcheck
      text: "SA1019:"
    - linters:
        - gosec
      source: "^\\s+tokenPath = \"/var/run/secrets/kubernetes.io/serviceaccount/token\"$"
      text: "G101:"
    - linters:
        - gosec
      source: "^\\s+return unsafe.Pointer\\(&ip\\[0\\]\\), nil$"
      text: "G103:"
    - linters:
        - gosec
      source: "^\\s+c.net = \\*\\(\\*uint32\\)\\(unsafe.Pointer\\(&n.IP\\[12\\]\\)\\)$"
      text: "G103:"
    - linters:
        - gosec
      source: "^\\s+c.net = \\*\\(\\*uint32\\)\\(unsafe.Pointer\\(&n.IP\\[0\\]\\)\\)$"
      text: "G103:"
    - linters:
        - gosec
      source: "^\\s+in, err := os.Open\\(srcFilepath\\)$"
      text: "G304:"
    - linters:
        - gosec
      source: "^\\s+existingCNIConfig, err := os.ReadFile\\(cniConfigFilepath\\)$"
      text: "G304:"
    - linters:
        - gosec
      source: "^\\s+fd, err := os.Open\\(nspath\\)$"
      text: "G304:"
    - linters:
        - gosec
      source: "^\\s+cniConfig, err := os.ReadFile\\(path\\)$"
      text: "G304:"
    - linters:
        - gosec
      source: "^\\s+f, _ := os.Open\\(path\\)$"
      text: "G304:"
    - linters:
        - gosec
      source: "^\\s+defer resp.Body.Close\\(\\)$"
      text: "G307:"
  exclude-use-default: false

